[server]
cors_origins = [
    "http://localhost:3000",
    "http://localhost:5173",
]

[security]
secret_key = "cQmSHQW7NyDgNNKxrh5V8uKgNF1Y4pqS"
algorithm = "HS256"
access_token_expire_minutes = 10080
admin_key_hash = "$2b$12$oPjteVKw7FLEVUmqGPJ0xe046x0vPRoHncLVksyKkYOOrwmZDhYwW"

[upload]
client_max_file_size_mb = 300
client_max_files_per_order = 5
